### ISSUE TITLE
Issues with OData Client Navigating API

### ISSUE THREAD

**Issue by ejlevin1** [SiberaIndustries/OData.Client.Manager#6]
I'm relatively new to the OData standard, so forgive me if this question is a NOOB.  I'm running into issues getting the client connected (which is resulting in a 500 error).  The below URLs show theway the URL structure is working.  Unfortunately, it doesn't even get past the metadata request (as it is the wrong URL), and if I set the metadata document explicitly, it still fails.  Is there a way to get this OData client to honor this URL navigation structure?  Excel and PowerBI work, but I am trying to get this for some ETL work.

Code:
```
var baseUrl = "https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/TOKEN_VALUE_HERE";
            var credentials = new NetworkCredential("some_username", "some_password");

            // Create the manager
            var config = new ODataManagerConfiguration(new Uri(baseUrl), credentials);
            var manager = new ODataManager(config);

            // Use the client of the manager (example of the typed fluent API syntax)
            var dx = ODataDynamic.Expression;
            IEnumerable<dynamic> entities = await manager.Client
                .For(dx.Issues)
                .FindEntriesAsync();
```

Produces this URL for the metadata request: https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/TOKEN_VALUE_HERE/$metadata -- resulting in a server side 500 error.

The below URLs are from my investigation via Postman.  You will notice that the metadata URL is specified in the response of the base URL, not just appending /$metadata to the URI.

URL : https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/TOKEN_VALUE_HERE
```
{
    "odata.metadata": "https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/$metadata?link=TOKEN_VALUE_HERE",
    "value": [
        {
            "name": "Issues",
            "url": "table-cn?name=Issues&s=TOKEN_VALUE_HERE"
        },
        {
            "name": "Worklogs",
            "url": "table-cn?name=Worklogs&s=TOKEN_VALUE_HERE"
        }
    ]
}
```

URL: https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/table-cn?name=Issues&s=TOKEN_VALUE_HERE
```
{
    "odata.metadata": "https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/$metadata#Issues",
    "value": [],
    "odata.nextLink": "https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/table-cn/next?aioSessionId=SESSION_VALUE_HERE&$skiptoken=0"
}
```

This URL is returning the Issues data: https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/table-cn/next?aioSessionId=SESSION_VALUE_HERE&$skiptoken=0

**Comment by SiberaIndustries** [comment]
> Is there a way to get this OData client to honor this URL navigation structure?

Probably not, because OData expects that the `$metadata` document can be requested as a path of the resource URL. That means if this is your resource URL:  
`https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/TOKEN_VALUE_HERE`
then the corresponding context URL should be this URL:  
`https://www.aioreports.com/aio-app/rest/aio/1.0/powerbi/export/TOKEN_VALUE_HERE/$metadata`

I am not sure which version of OData you are using, but you can get detailed information [in the current and official OData protocol specification](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ContextURL).

If you still need to customize the context URL, then I would like to ask you to open a feature request in the [Simple OData Client](https://github.com/simple-odata-client/Simple.OData.Client) repository, because this library is based on it.
